version: '2'
services:
    web:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile
        command: python runserver.py
        volumes:
            - ../src:/code:ro
        ports:
            - "5000:5000"
        links:
            - redis
        environment:
            - WEB_HOST=0.0.0.0
    redis:
        image: redis
        ports:
            - "6379:6379"
